on:
  workflow_dispatch:
    inputs:
      type:
        required: true
        type: choice
        description: Release type
        options: 
        - major
        - minor
        - patch

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: zwaldowski/semver-release-action@v3
        id: semantic-version
        with:
          bump: ${{ github.event.inputs.type }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.semantic-version.outputs.version }}
          release_name: Release ${{ steps.semantic-version.outputs.version }}
          draft: false
          prerelease: false
