on:
  release:
    types: [created]
  push:
    branches:
    - main

name: Deploy code

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: deploy prod
        if: ${{ github.event_name == 'release' }}
        run:
          echo "Deploy production"
      - name: deploy dev + staging
        if: ${{ github.event_name == 'push' }}
        run:
          echo "Deploy dev + staging"
